-- MySQL Script generated by MySQL Workbench
-- Wed Jul  8 12:35:27 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema exercici6
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema exercici6
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `exercici6` DEFAULT CHARACTER SET utf8 ;
USE `exercici6` ;

-- -----------------------------------------------------
-- Table `exercici6`.`proveïdor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercici6`.`proveïdor` (
  `nom` VARCHAR(45) NOT NULL,
  `carrer` VARCHAR(45) NULL,
  `numero` INT NULL,
  `pis` INT NULL,
  `porta` INT NULL,
  `ciutat` VARCHAR(45) NULL,
  `codi_postal` INT NULL,
  `pais` VARCHAR(45) NULL,
  `telefon` INT NULL,
  `fax` INT NULL,
  `NIF` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nom`, `NIF`),
  UNIQUE INDEX `NIF_UNIQUE` (`NIF` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercici6`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercici6`.`client` (
  `nom_client` VARCHAR(45) NOT NULL,
  `adreça` VARCHAR(45) NULL,
  `telefon` INT NULL,
  `mail` VARCHAR(45) NULL,
  `data` DATE NULL,
  `recomanacio` VARCHAR(45) NULL,
  `empleat` VARCHAR(45) NULL,
  PRIMARY KEY (`nom_client`),
  UNIQUE INDEX `nom_UNIQUE` (`nom_client` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercici6`.`ulleres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercici6`.`ulleres` (
  `marca` VARCHAR(45) NOT NULL,
  `graduacio` VARCHAR(45) NULL,
  `tipus_muntura` VARCHAR(45) NULL,
  `color_muntura` VARCHAR(45) NULL,
  `color_vidres` VARCHAR(45) NULL,
  `preu` INT NULL,
  `proveïdor_nom` VARCHAR(45) NOT NULL,
  `proveïdor_NIF` VARCHAR(45) NOT NULL,
  `client_nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`marca`),
  UNIQUE INDEX `marca_UNIQUE` (`marca` ASC) VISIBLE,
  INDEX `fk_ulleres_proveïdor_idx` (`proveïdor_nom` ASC, `proveïdor_NIF` ASC) VISIBLE,
  INDEX `fk_ulleres_client1_idx` (`client_nom` ASC) VISIBLE,
  CONSTRAINT `fk_ulleres_proveïdor`
    FOREIGN KEY (`proveïdor_nom` , `proveïdor_NIF`)
    REFERENCES `exercici6`.`proveïdor` (`nom` , `NIF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ulleres_client1`
    FOREIGN KEY (`client_nom`)
    REFERENCES `exercici6`.`client` (`nom_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
